version: "3.9"
services:
  db:
    platform: linux/x86_64
    # DockerHubにあるmysql8.0のイメージを使用
    image: mysql:8.0.28
    # MySQL8.0以降の認証方式に元に戻す設定
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
    # .envの環境変数を展開してMYSQLコンテナのパスワードを登録
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
    networks:
      - vite_rails_net
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
        #  args
        #  WORKDIR: app
    volumes:
      - ./frontend/vite-project:/app/vite-project
    ports:
      - 5173:5173
    depends_on:
      - backend
    tty: true
    command: yarn dev --host
    networks:
      - vite_rails_net
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./backend:/app
    environment:
      TZ: Asia/Tokyo
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
    ports:
      - 3000:3000
    depends_on:
      - db
    tty: true
    stdin_open: true
    networks:
      - vite_rails_net
volumes:
  mysql-data:
    driver: local
networks:
  vite_rails_net: