=begin
API Title

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0
Generated by: https://github.com/openapitools/openapi-generator.git

=end
class SchedulesController < ApplicationController
  before_action :authenticate_api_user!

  def create
    schedule = Schedule.create(lecture_id: params[:lecture_id], user_id: current_api_user.id)
    render json: schedule
  end

  def destroy
    schedule = Schedule.delete(params[:id])
    render json: schedule
  end

  def index
    lectures = Lecture.joins(:schedules).joins(:teacher)
                      .select('lectures.*, schedules.id as schedules_id, CONCAT(users.last_name, " ", users.first_name) as teacher_name')
                      .filter_period_by(params[:period])
                      .filter_dow_by(params[:day_of_week])
                      .filter_title_by(params[:title])
                      .where(schedules: { user_id: current_api_user.id })
                      .all
    render json: lectures
  end

end
